# coding: utf-8

"""
    oxd-server

    oxd-server  # noqa: E501

    OpenAPI spec version: 4.2
    Contact: yuriyz@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.web_finger_link import WebFingerLink  # noqa: E501
from swagger_client.rest import ApiException


class TestWebFingerLink(unittest.TestCase):
    """WebFingerLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebFingerLink(self):
        """Test WebFingerLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.web_finger_link.WebFingerLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
